/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package it.ariadne.prova.registration.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.ariadne.prova.registration.model.PRRegistration;
import it.ariadne.prova.registration.service.PRRegistrationLocalServiceUtil;

/**
 * The extended model base implementation for the PRRegistration service. Represents a row in the &quot;prreg_PRRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PRRegistrationImpl}.
 * </p>
 *
 * @author Politi
 * @see PRRegistrationImpl
 * @see it.ariadne.prova.registration.model.PRRegistration
 * @generated
 */
public abstract class PRRegistrationBaseImpl extends PRRegistrationModelImpl
	implements PRRegistration {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p r registration model instance should use the {@link PRRegistration} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			PRRegistrationLocalServiceUtil.addPRRegistration(this);
		}
		else {
			PRRegistrationLocalServiceUtil.updatePRRegistration(this);
		}
	}
}