/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package it.ariadne.prova.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PRRegistration service. Represents a row in the &quot;prreg_PRRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ariadne.prova.registration.model.impl.PRRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ariadne.prova.registration.model.impl.PRRegistrationImpl}.
 * </p>
 *
 * @author Politi
 * @see PRRegistration
 * @see it.ariadne.prova.registration.model.impl.PRRegistrationImpl
 * @see it.ariadne.prova.registration.model.impl.PRRegistrationModelImpl
 * @generated
 */
public interface PRRegistrationModel extends BaseModel<PRRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a p r registration model instance should use the {@link PRRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this p r registration.
	 *
	 * @return the primary key of this p r registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this p r registration.
	 *
	 * @param primaryKey the primary key of this p r registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registration ID of this p r registration.
	 *
	 * @return the registration ID of this p r registration
	 */
	public long getRegistrationId();

	/**
	 * Sets the registration ID of this p r registration.
	 *
	 * @param registrationId the registration ID of this p r registration
	 */
	public void setRegistrationId(long registrationId);

	/**
	 * Returns the pr user ID of this p r registration.
	 *
	 * @return the pr user ID of this p r registration
	 */
	public long getPrUserId();

	/**
	 * Sets the pr user ID of this p r registration.
	 *
	 * @param prUserId the pr user ID of this p r registration
	 */
	public void setPrUserId(long prUserId);

	/**
	 * Returns the pr user uuid of this p r registration.
	 *
	 * @return the pr user uuid of this p r registration
	 * @throws SystemException if a system exception occurred
	 */
	public String getPrUserUuid() throws SystemException;

	/**
	 * Sets the pr user uuid of this p r registration.
	 *
	 * @param prUserUuid the pr user uuid of this p r registration
	 */
	public void setPrUserUuid(String prUserUuid);

	/**
	 * Returns the date purchased of this p r registration.
	 *
	 * @return the date purchased of this p r registration
	 */
	public Date getDatePurchased();

	/**
	 * Sets the date purchased of this p r registration.
	 *
	 * @param datePurchased the date purchased of this p r registration
	 */
	public void setDatePurchased(Date datePurchased);

	/**
	 * Returns the how hear of this p r registration.
	 *
	 * @return the how hear of this p r registration
	 */
	@AutoEscape
	public String getHowHear();

	/**
	 * Sets the how hear of this p r registration.
	 *
	 * @param howHear the how hear of this p r registration
	 */
	public void setHowHear(String howHear);

	/**
	 * Returns the where purchased of this p r registration.
	 *
	 * @return the where purchased of this p r registration
	 */
	@AutoEscape
	public String getWherePurchased();

	/**
	 * Sets the where purchased of this p r registration.
	 *
	 * @param wherePurchased the where purchased of this p r registration
	 */
	public void setWherePurchased(String wherePurchased);

	/**
	 * Returns the serial number of this p r registration.
	 *
	 * @return the serial number of this p r registration
	 */
	@AutoEscape
	public String getSerialNumber();

	/**
	 * Sets the serial number of this p r registration.
	 *
	 * @param serialNumber the serial number of this p r registration
	 */
	public void setSerialNumber(String serialNumber);

	/**
	 * Returns the product ID of this p r registration.
	 *
	 * @return the product ID of this p r registration
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this p r registration.
	 *
	 * @param productId the product ID of this p r registration
	 */
	public void setProductId(long productId);

	/**
	 * Returns the company ID of this p r registration.
	 *
	 * @return the company ID of this p r registration
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this p r registration.
	 *
	 * @param companyId the company ID of this p r registration
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this p r registration.
	 *
	 * @return the group ID of this p r registration
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this p r registration.
	 *
	 * @param groupId the group ID of this p r registration
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.ariadne.prova.registration.model.PRRegistration prRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ariadne.prova.registration.model.PRRegistration> toCacheModel();

	@Override
	public it.ariadne.prova.registration.model.PRRegistration toEscapedModel();

	@Override
	public it.ariadne.prova.registration.model.PRRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}